// Project & Thread management
// Persists to a JSON file via Tauri backend

import { invoke } from "@tauri-apps/api/core";

export interface Project {
  id: string;
  title: string;
  workspaceRoot: string;
  createdAt: string;
}

export interface ThreadUsage {
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
}

export interface Thread {
  id: string;
  projectId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messages: ThreadMessage[];
  sessionId?: string;
  provider?: string;
  model?: string;
  permissionMode?: string;
  usage?: ThreadUsage;
  archivedAt?: string;
  titleAutoGenerated?: boolean;
}

export interface ThreadMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: number;
}

export interface SessionState {
  rootPath: string | null;
  openFiles: string[];
  activeFile: string | null;
}

export interface ProjectStore {
  projects: Project[];
  threads: Thread[];
  session?: SessionState;
}

let store: ProjectStore = { projects: [], threads: [] };
let onChangeCallback: (() => void) | null = null;

function uid(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function autoTitleFromMessage(content: string): string {
  const cleaned = content
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]+`/g, " ")
    .replace(/[#>*_\-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) {
    return "New thread";
  }

  const firstSentence = cleaned.split(/[.!?\n]/)[0]?.trim() || cleaned;
  const normalized = firstSentence
    .replace(/^(please|can you|could you|help me|i need to)\s+/i, "")
    .trim();
  const title = normalized || cleaned;
  return title.slice(0, 64) + (title.length > 64 ? "..." : "");
}

function normalizeStore() {
  store.projects = store.projects || [];
  store.threads = (store.threads || []).map((thread) => {
    const updatedAt = thread.updatedAt || thread.createdAt || new Date().toISOString();
    return {
      ...thread,
      updatedAt,
      titleAutoGenerated: thread.titleAutoGenerated ?? thread.title === "New thread",
      messages: thread.messages || [],
    };
  });
}

// ---- Persistence ----

export async function loadProjects(): Promise<ProjectStore> {
  try {
    const data: string = await invoke("load_project_store");
    store = JSON.parse(data);
  } catch {
    store = { projects: [], threads: [] };
  }
  normalizeStore();
  return store;
}

async function saveStore() {
  try {
    await invoke("save_project_store", { data: JSON.stringify(store) });
  } catch (e) {
    console.error("Failed to save project store:", e);
  }
  onChangeCallback?.();
}

export function onStoreChange(cb: () => void) {
  onChangeCallback = cb;
}

// ---- Projects ----

export function getProjects(): Project[] {
  return store.projects;
}

export function getProject(id: string): Project | undefined {
  return store.projects.find((p) => p.id === id);
}

export function findProjectByRoot(root: string): Project | undefined {
  return store.projects.find((p) => p.workspaceRoot === root);
}

export async function createProject(title: string, workspaceRoot: string): Promise<Project> {
  const existing = findProjectByRoot(workspaceRoot);
  if (existing) return existing;

  const project: Project = {
    id: uid(),
    title,
    workspaceRoot,
    createdAt: new Date().toISOString(),
  };
  store.projects.push(project);
  await saveStore();
  return project;
}

export async function deleteProject(id: string) {
  store.projects = store.projects.filter((p) => p.id !== id);
  store.threads = store.threads.filter((t) => t.projectId !== id);
  await saveStore();
}

// ---- Threads ----

function sortThreads(threads: Thread[]): Thread[] {
  return threads.sort((a, b) => new Date(b.updatedAt || b.createdAt).getTime() - new Date(a.updatedAt || a.createdAt).getTime());
}

export function getThreadsForProject(projectId: string): Thread[] {
  return sortThreads(
    store.threads.filter((thread) => thread.projectId === projectId && !thread.archivedAt),
  );
}

export function getArchivedThreadsForProject(projectId: string): Thread[] {
  return sortThreads(
    store.threads.filter((thread) => thread.projectId === projectId && !!thread.archivedAt),
  );
}

export function getThread(id: string): Thread | undefined {
  return store.threads.find((t) => t.id === id);
}

export async function createThread(projectId: string, title: string = "New thread"): Promise<Thread> {
  const now = new Date().toISOString();
  const thread: Thread = {
    id: uid(),
    projectId,
    title,
    createdAt: now,
    updatedAt: now,
    messages: [],
    titleAutoGenerated: title === "New thread",
  };
  store.threads.push(thread);
  await saveStore();
  return thread;
}

export async function deleteThread(id: string) {
  store.threads = store.threads.filter((t) => t.id !== id);
  await saveStore();
}

export async function renameThread(id: string, title: string) {
  const thread = store.threads.find((t) => t.id === id);
  if (thread) {
    thread.title = title.trim() || thread.title;
    thread.titleAutoGenerated = false;
    thread.updatedAt = new Date().toISOString();
    await saveStore();
  }
}

export async function archiveThread(id: string) {
  const thread = store.threads.find((t) => t.id === id);
  if (thread && !thread.archivedAt) {
    thread.archivedAt = new Date().toISOString();
    thread.updatedAt = thread.archivedAt;
    await saveStore();
  }
}

export async function unarchiveThread(id: string) {
  const thread = store.threads.find((t) => t.id === id);
  if (thread && thread.archivedAt) {
    delete thread.archivedAt;
    thread.updatedAt = new Date().toISOString();
    await saveStore();
  }
}

export async function setThreadSessionId(threadId: string, sessionId: string) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread) {
    thread.sessionId = sessionId;
    await saveStore();
  }
}

export async function setThreadModelAndPermission(threadId: string, model: string, permissionMode: string) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread) {
    thread.model = model;
    thread.permissionMode = permissionMode;
    await saveStore();
  }
}

export async function clearThreadSessionId(threadId: string) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread) {
    delete thread.sessionId;
    await saveStore();
  }
}

export function getThreadSessionId(threadId: string): string | undefined {
  return store.threads.find((t) => t.id === threadId)?.sessionId;
}

export async function setThreadProvider(threadId: string, provider: string) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread && !thread.provider) {
    thread.provider = provider;
    await saveStore();
  }
}

export function getThreadProvider(threadId: string): string | undefined {
  return store.threads.find((t) => t.id === threadId)?.provider;
}

export async function forkThread(threadId: string, newProvider: string, titleSuffix?: string): Promise<Thread | null> {
  const source = store.threads.find((t) => t.id === threadId);
  if (!source) return null;

  const suffix = titleSuffix ?? `${newProvider === "codex" ? "Codex" : "Claude"} fork`;
  const now = new Date().toISOString();
  const forked: Thread = {
    id: uid(),
    projectId: source.projectId,
    title: `${source.title} (${suffix})`,
    createdAt: now,
    updatedAt: now,
    messages: source.messages.map((message) => ({ ...message })),
    provider: newProvider,
    titleAutoGenerated: false,
  };
  store.threads.push(forked);
  await saveStore();
  return forked;
}

export async function addThreadUsage(threadId: string, inputTokens: number, outputTokens: number, costUsd: number) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread) {
    if (!thread.usage) {
      thread.usage = { inputTokens: 0, outputTokens: 0, costUsd: 0 };
    }
    thread.usage.inputTokens += inputTokens;
    thread.usage.outputTokens += outputTokens;
    thread.usage.costUsd += costUsd;
    await saveStore();
  }
}

export function getThreadUsage(threadId: string): ThreadUsage {
  const thread = store.threads.find((t) => t.id === threadId);
  return thread?.usage || { inputTokens: 0, outputTokens: 0, costUsd: 0 };
}

export async function addMessageToThread(threadId: string, role: "user" | "assistant", content: string) {
  const thread = store.threads.find((t) => t.id === threadId);
  if (thread) {
    thread.messages.push({ role, content, timestamp: Date.now() });
    thread.updatedAt = new Date().toISOString();
    if (role === "user" && thread.titleAutoGenerated) {
      thread.title = autoTitleFromMessage(content);
    }
    if (thread.archivedAt) {
      delete thread.archivedAt;
    }
    await saveStore();
  }
}

// ---- Session Persistence ----

export async function saveSession(rootPath: string | null, openFiles: string[], activeFile: string | null) {
  store.session = { rootPath, openFiles, activeFile };
  await saveStore();
}

export function getSession(): SessionState | null {
  return store.session || null;
}

// ---- Time formatting ----

export function timeAgo(dateStr: string): string {
  const seconds = Math.floor((Date.now() - new Date(dateStr).getTime()) / 1000);
  if (seconds < 60) return "now";

  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m`;

  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h`;

  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d`;

  const weeks = Math.floor(days / 7);
  if (weeks < 5) return `${weeks}w`;

  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo`;

  const years = Math.floor(days / 365);
  return `${years}y`;
}
